.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "CHECKSUMS" "1" "August 2016" "checksums developers" ""
.
.SH "NAME"
\fBchecksums\fR \- Tool for making/verifying checksums of directory trees
.
.SH "SYNOPSIS"
\fBchecksums\fR [OPTIONS] [DIRECTORY]
.
.SH "DESCRIPTION"
Tool for making/verifying checksums of directory trees\.
.
.P
Use the generated checksums to automatically verify file/directory tree correctness\.
.
.P
All output is wrapped to 80 columns\.
.
.SH "OPTIONS"
\-a \-\-algorithm <\fIalgorithm\fR>
.
.IP "" 4
.
.nf

Set the hashing algorithm to use\.

Supported algorithms: SHA1, SHA2\-256, SHA2\-512, SHA3\-256, SHA3\-512, BLAKE,
                      BLAKE2, CRC8, CRC16, CRC32, CRC64, MD5, MD6\-128,
                      MD6\-256, MD6\-512, XOR8
.
.fi
.
.IP "" 0
.
.P
\-c \-\-create
.
.IP "" 4
.
.nf

Create directory hashes, rather than verifying them\.

Directory hashes are output to the output file, which, if not specified, will
be "`DIRECTORY`\.hash"\.

Will fail if the output file already exists and `\-\-force` is not specified\.

Exclusive with `\-\-verify`\. Overrides `\-\-verify`\.
.
.fi
.
.IP "" 0
.
.P
\-v \-\-verify
.
.IP "" 4
.
.nf

Verify directory hashes\. Default\.

Exclusive with `\-\-create`\. Overrides `\-\-create`\.
.
.fi
.
.IP "" 0
.
.P
\-d \-\-depth <\fIdepth\fR>
.
.IP "" 4
.
.nf

Set max recursion depth to `depth`\. Default: 0\.

Exclusive with `\-\-recursive`\. Overrides `\-\-recursive`\.
.
.fi
.
.IP "" 0
.
.P
\-r \-\-recursive
.
.IP "" 4
.
.nf

Set max recursion depth to infinity\.

Exclusive with `\-\-depth`\. Overrides `\-\-depth`\.
.
.fi
.
.IP "" 0
.
.P
\-\-force
.
.IP "" 4
.
.nf

Override output file in `\-\-create` mode\. No meaning in `\-\-verify` mode\.
.
.fi
.
.IP "" 0
.
.P
\-\-follow\-symlinks
.
.IP "" 4
.
.nf

  Recurse down symlinks\. Default\.
.
.fi
.
.IP "" 0
.
.P
\-\-no\-follow\-symlinks
.
.IP "" 4
.
.nf

  Don\'t recurse down symlinks\.
.
.fi
.
.IP "" 0
.
.P
\-i \-\-ignore <<filename[,filename2][,filename3][,filenameN]\.\.\.>>\.\.\.
.
.IP "" 4
.
.nf

Add filename(s) to ignored files list\. Default: none\.

Ignored files are marked as such\.

Accepted multiple times\.
.
.fi
.
.IP "" 0
.
.P
\-j \-\-jobs [jobs]
.
.IP "" 4
.
.nf

Amount of threads used for hashing\. Default: # of CPU threads

One thread can hash one file at a time, potentially speeding up hashing
up to `jobs` times\.

No/empty value: # of CPU threads\. \-1: Infinite
.
.fi
.
.IP "" 0
.
.P
[DIRECTORY]
.
.IP "" 4
.
.nf

Directory to create/verify hash for\. Default: current workdir\.
.
.fi
.
.IP "" 0
.
.SH "EXAMPLES"
\fBchecksums\fR [\fB\-v\fR] [\fB\-f\fR \fIinfile\fR]
.
.IP "" 4
.
.nf

Verify the current directory tree against the saved hashes\.

`\-v` is not necessary as it\'s the default\.

*infile* defaults to "`DIRECTORY`\.hash"

Example output:
  File added: "file_that_was_not_here_before"
  File removed: "file_that_was_here_before_but_not_now"
  File ignored: "file_specified_with_ignore_now_or_during_creation"

  File "file_that_did_not_change" matches
  File "changed_file" doesn\'t match
    Was: 8313958F86F7B15D4775D12886D479C1CFAAA111
    Is : FCFC1548B30B5ACB25A7421D068E12F07DF74DCC
.
.fi
.
.IP "" 0
.
.P
\fBchecksums\fR \fB\-c\fR [\fB\-f\fR \fIoutfile\fR] [\fB\-\-force\fR]
.
.IP "" 4
.
.nf

Create hashes of the current directory tree for later verification\.

*outfile* defaults to "`DIRECTORY`\.hash"\.

Use `\-\-force` to override *outfile*\.

Example output: none; hashes file creation does not output any data\.
*outfile* contents:
  a_file\.txt      8313958F86F7B15D4775D12886D479C1CFAAA111
  *outfile*\.hash  \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
  different_file  8D742C1F2D39434771039E98AD854C72F91FCCA5
.
.fi
.
.IP "" 0
.
.P
\fBchecksums\fR [\fB\-d\fR \fIdepth\fR] [\fB\-r\fR] [\fBOTHER OPTIONS\fR]
.
.IP "" 4
.
.nf

Recurse *depth* or infinity directories down\.

Example output for *depth*=2:
  File "dir1/dir2/file" matches
  File "dir1/file" matches
  File "file" matches
.
.fi
.
.IP "" 0
.
.SH "AUTHOR"
Written by nabijaczleweli <\fInabijaczleweli@gmail\.com\fR> and Zachary Dremann <\fIdremann@gmail\.com\fR>
.
.SH "REPORTING BUGS"
<\fIhttps://github\.com/nabijaczleweli/checksums/issues\fR>
.
.SH "SEE ALSO"
<\fIhttps://github\.com/nabijaczleweli/checksums\fR>
